# Generated by Django 2.0.3 on 2018-03-10 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=5)),
                ('volume', models.FloatField()),
                ('open', models.FloatField()),
                ('close', models.FloatField()),
            ],
        ),
    ]
